<?php
return array(
    'BLOG_ITEM_TYPE_WORD'=>1,
    'BLOG_ITEM_TYPE_PICTURE'=>2,
    'BLOG_ITEM_TYPE_VIDEO'=>3,
    'BLOG_ITEM_TYPE_LINK'=>4,

    'LIKE_TYPE_LIKE'=>5,
    'LIKE_TYPE_REPOST'=>6,
    'LIKE_TYPE_COMMENT'=>7
);